In [1]:
import pandas as pd

In [15]:
df = pd.read_excel(r"C:\Users\akash\Documents\data analyst\data dna project\Hotel Bookings.xlsx")
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,date,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,2015-July-1,1,0,0,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,2015-July-1,1,0,0,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,2015-July-1,1,0,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,2015-July-1,1,0,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,2015-July-1,1,0,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,2017-August-30,30,2,5,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,2017-August-31,31,2,5,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,2017-August-31,31,2,5,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,2017-August-31,31,2,5,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,2017-August-29,29,2,7,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [16]:
df.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
date                                   0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

In [17]:
df.fillna(0,inplace=True)

In [19]:
df = df.drop(columns = ["arrival_date_year","arrival_date_month","arrival_date_day_of_month"])
df

,hotel,is_canceled,lead_time,arrival_date_week_number,date,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,27,2015-July-1,0,0,2,0.0,0,...,No Deposit,0.0,0.0,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,27,2015-July-1,0,0,2,0.0,0,...,No Deposit,0.0,0.0,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,27,2015-July-1,0,1,1,0.0,0,...,No Deposit,0.0,0.0,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,27,2015-July-1,0,1,1,0.0,0,...,No Deposit,304.0,0.0,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,27,2015-July-1,0,2,2,0.0,0,...,No Deposit,240.0,0.0,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,35,2017-August-30,2,5,2,0.0,0,...,No Deposit,394.0,0.0,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,35,2017-August-31,2,5,3,0.0,0,...,No Deposit,9.0,0.0,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,35,2017-August-31,2,5,2,0.0,0,...,No Deposit,9.0,0.0,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,35,2017-August-31,2,5,2,0.0,0,...,No Deposit,89.0,0.0,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,35,2017-August-29,2,7,2,0.0,0,...,No Deposit,9.0,0.0,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [25]:
df["meal"].replace("Undefined","Sc",inplace=True)

In [31]:
df["meal"].replace("Sc","SC",inplace=True)

In [32]:
df['meal'].unique()

array(['BB', 'FB', 'HB', 'SC'], dtype=object)

In [33]:
delete = (df["adults"]==0) & (df["children"]==0) & (df["babies"]==0)

In [36]:
data = df[~delete]
data

,hotel,is_canceled,lead_time,arrival_date_week_number,date,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,27,2015-July-1,0,0,2,0.0,0,...,No Deposit,0.0,0.0,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,27,2015-July-1,0,0,2,0.0,0,...,No Deposit,0.0,0.0,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,27,2015-July-1,0,1,1,0.0,0,...,No Deposit,0.0,0.0,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,27,2015-July-1,0,1,1,0.0,0,...,No Deposit,304.0,0.0,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,27,2015-July-1,0,2,2,0.0,0,...,No Deposit,240.0,0.0,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,35,2017-August-30,2,5,2,0.0,0,...,No Deposit,394.0,0.0,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,35,2017-August-31,2,5,3,0.0,0,...,No Deposit,9.0,0.0,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,35,2017-August-31,2,5,2,0.0,0,...,No Deposit,9.0,0.0,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,35,2017-August-31,2,5,2,0.0,0,...,No Deposit,89.0,0.0,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,35,2017-August-29,2,7,2,0.0,0,...,No Deposit,9.0,0.0,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [38]:
data.shape

(119210, 30)

In [39]:
data = data.drop(columns=["reservation_status","reservation_status_date" ])

In [40]:
data

,hotel,is_canceled,lead_time,arrival_date_week_number,date,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,...,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests
0,Resort Hotel,0,342,27,2015-July-1,0,0,2,0.0,0,...,C,3,No Deposit,0.0,0.0,0,Transient,0.00,0,0
1,Resort Hotel,0,737,27,2015-July-1,0,0,2,0.0,0,...,C,4,No Deposit,0.0,0.0,0,Transient,0.00,0,0
2,Resort Hotel,0,7,27,2015-July-1,0,1,1,0.0,0,...,C,0,No Deposit,0.0,0.0,0,Transient,75.00,0,0
3,Resort Hotel,0,13,27,2015-July-1,0,1,1,0.0,0,...,A,0,No Deposit,304.0,0.0,0,Transient,75.00,0,0
4,Resort Hotel,0,14,27,2015-July-1,0,2,2,0.0,0,...,A,0,No Deposit,240.0,0.0,0,Transient,98.00,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,35,2017-August-30,2,5,2,0.0,0,...,A,0,No Deposit,394.0,0.0,0,Transient,96.14,0,0
119386,City Hotel,0,102,35,2017-August-31,2,5,3,0.0,0,...,E,0,No Deposit,9.0,0.0,0,Transient,225.43,0,2
119387,City Hotel,0,34,35,2017-August-31,2,5,2,0.0,0,...,D,0,No Deposit,9.0,0.0,0,Transient,157.71,0,4
119388,City Hotel,0,109,35,2017-August-31,2,5,2,0.0,0,...,A,0,No Deposit,89.0,0.0,0,Transient,104.40,0,0
119389,City Hotel,0,205,35,2017-August-29,2,7,2,0.0,0,...,A,0,No Deposit,9.0,0.0,0,Transient,151.20,0,2

In [42]:
data.to_excel("data.xlsx")